# Generated by Django 4.0.5 on 2022-06-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('press', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'book_books',
            },
        ),
    ]
