# Generated by Django 4.0.5 on 2022-06-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='readBook',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('readname', models.CharField(max_length=255, null=True)),
                ('bookid', models.CharField(max_length=30, null=True)),
                ('bookname', models.CharField(max_length=255, null=True)),
                ('readtime', models.CharField(blank=True, max_length=100, null=True)),
                ('returntime', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'book_read',
            },
        ),
    ]
